# 4ms-lifetime modification for ICARUS configs
# Revision date: July 19, 2024

__meta__:
  name: "4ms"
  version: "240719"
  date: "2024-07-19"
  description: "4ms lifetime calibration"
  applies_to: [mc]
  compatible_with:
    post: "<=250115"
  conflicts_with: [data, 8ms]

override:
  # Change calibration lifetime to 4 ms
  post.apply_calibrations.lifetime.lifetime: 4000 # us
