# ICARUS full chain configuration with collection-only model
# Revision date: February 12, 2026

include:
  - base/base_240719.yaml
  - io/io_240812.yaml
  - model/model_co_260212.yaml
  - post/post_250625.yaml
