# NuMI-specific modification for ICARUS configs
# Revision date: July 19, 2024

__meta__:
  name: "numi"
  version: "240719"
  date: "2024-07-19"
  description: "NuMI-specific settings (wider flash matching window)"
  applies_to: [mc, data]
  compatible_with:
    post: "<=250115"

override:
  # Use NuMI-specific flash matching configuration
  post.flash_match.cfg: !path flashmatch/flashmatch_numi_230930.cfg
