# Single-cryostat modification for ICARUS configs
# Revision date: July 19, 2024

include: patch_single_common.yaml

override:
  # Use the NuMI-specific flashmatch configuration (MPV generation window matches NuMI)
  post.flash_match.cfg: flashmatch/flashmatch_numi_230930.cfg 
