# Transparency-correction modification for ICARUS configs
# Revision date: July 19, 2024

override:
  # Add transparency correction
  post.apply_calibrations.transparency:
    run_id: 9435
    transparency_db: /sdf/data/neutrino/icarus/db/v09_84_01/tpc_yz_correction_data.db