# 4ms-lifetime lite-output configuration for ICARUS, collection-only
# Revision date: June 25, 2025

include:
  - ../icarus_full_chain_co_250625.yaml
  - ../modifier/lite/mod_lite_240719.yaml
  - ../modifier/4ms/mod_4ms_250303.yaml
