# IO configuration for ProtoDUNE-SP
# Revision date: February 10, 2026

__meta__:
  version: "260210"
  date: "2026-02-10"
  description: "IO configuration for ProtoDUNE-SP February 2026"
  compatible_with:
    base: ">=260210"
  tags: [no-ppn-point-tagging]

include: io_common.yaml

override:
  # No flashes or CRT hits just yet
  io.loader.dataset.schema-:
    - flashes
    - crthits
  io.writer.keys-:
    - flashes
    - crthits
