# IO configuration for 2x2
# Revision date: July 19, 2024

__meta__:
  version: "240719"
  date: "2024-07-19"
  description: "IO configuration for 2x2 July 2024"
  compatible_with:
    base: ">=240719"
  tags: [ppn-point-tagging]

include: io_common.yaml

override:
  # Include point tagging in PPN label parser
  io.loader.dataset.schema.ppn_label.include_point_tagging: true
