# Lite-output, unblind configuration for ICARUS, collection-only
# Revision date: March 3, 2025

include:
  - ../full_chain_co_250303.yaml
  - ../modifier/data/mod_data_250303.yaml
  - ../modifier/lite/mod_lite_240719.yaml
  - ../modifier/unblind/mod_unblind_240719.yaml
