# 4ms-lifetime lite-output configuration for ICARUS, collection-only
# Revision date: January 15, 2025

include:
  - ../full_chain_co_250115.yaml
  - ../modifier/lite/mod_lite_240719.yaml
  - ../modifier/4ms/mod_4ms_240719.yaml
