# Lite-output modification for ND-LAr configs
# Revision date: August 19, 2024

__meta__:
  name: "lite"
  version: "240819"
  date: "2024-08-19"
  description: "Lite-output configuration"
  applies_to: [mc, data]
  compatible_with:
    io: ">=240819"

include: mod_lite_common.yaml
