# Overlay modification for generic simulation configs
# Include this after the main config to overlay four images (no heavy data products)

override:
  # Overlay collate function
  io.loader.collate_fn:
    name: all
    overlay:
      multiplicity: 4

  # Remove currently problematic data products for overlays
  io.loader.dataset.schema-:
    - run_info

  # Remove problematic writers for overlays
  io.writer.keys-:
    - run_info
    - trigger
