# Single-module modification for 2x2 configs
# Revision date: July 19, 2024

__meta__:
  name: "single"
  version: "240719"
  date: "2024-07-19"
  description: "Single-module configuration"
  applies_to: [mc]
  compatible_with:
    io: ">=240719"

include: mod_single_common.yaml
