# ICARUS full chain configuration with collection-only model
# Revision date: August 12, 2024

include:
  - base/base_240719.yaml
  - io/io_240812.yaml
  - model/model_co_250115.yaml
  - post/post_250115.yaml
