# Lite-output, unblind configuration for ICARUS, collection-only
# Revision date: January 15, 2025

include: 
  - icarus_full_chain_co_250115.yaml
  - patch/data/patch_data_250115.yaml
  - patch/lite/patch_lite_240719.yaml
  - patch/unblind/patch_unblind_240719.yaml
