# Data-only, NuMI-specific configuration for ICARUS
# Revision date: January 15, 2025

include: 
  - icarus_full_chain_250115.yaml
  - modifier/data/mod_data_250115.yaml
  - modifier/numi/mod_numi_240719.yaml
