# 8ms-lifetime lite-output configuration for ICARUS, collection-only
# Revision date: March 3, 2025

include:
  - icarus_full_chain_co_250303.yaml
  - modifier/lite/mod_lite_240719.yaml
  - modifier/8ms/mod_8ms_250303.yaml
