# IO configuration for generic simulations
# Revision date: July 19, 2024

__meta__:
  version: "240719"
  date: "2024-07-19"
  description: "IO configuration for generic simulations July 2024"
  compatible_with:
    base: ">=240719"
  tags: [no-ppn-point-tagging]

include: io_common.yaml
