# IO configuration for generic simulations
# Revision date: August 5, 2024

__meta__:
  version: "240805"
  date: "2024-08-05"
  description: "IO configuration for generic simulations August 2024"
  compatible_with:
    base: ">=240718"
  tags: [no-ppn-point-tagging]

include: io_common.yaml

override:
  # Exclude point tagging in PPN label parser
  io.loader.dataset.schema.ppn_label.include_point_tagging: false
