# IO configuration for DUNE10kt-1x2x6
# Revision date: February 2, 2026

__meta__:
  version: "260202"
  date: "2026-02-02"
  description: "IO configuration for DUNE10kt-1x2x6 February 2026"
  compatible_with:
    base: ">=260202"
  tags: [no-ppn-point-tagging]

include: io_common.yaml

override:
  # No flashes or CRT hits just yet
  io.loader.dataset.schema-:
    - flashes
    - crthits
  io.writer.keys-:
    - flashes
    - crthits
